In [1]:
import numpy as np

In [2]:
simple_list = [1,2,3]

In [3]:
np.array(simple_list)

array([1, 2, 3])

In [4]:
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,21,5)

array([ 0,  5, 10, 15, 20])

In [13]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [38]:
a = np.eye(5)

In [22]:
np.random.rand(3,2)

array([[0.22396285, 0.19462321],
       [0.00416315, 0.52510327],
       [0.46740638, 0.46444863]])

In [41]:
a1 = np.random.randn(3,2)

In [24]:
np.random.randint(5,20)

13

In [25]:
np.random.randint(5,6)

5

In [26]:
np.random.randint(5,20,10)

array([17, 10, 14, 11, 14, 15, 18,  9,  9, 16])

In [27]:
sample_array = np.arange(30)

In [28]:
rand_array = np.random.randint(0,100,20)

In [29]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [30]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [31]:
rand_array.max()

91

In [32]:
rand_array

array([91, 78, 14, 55, 43, 41, 44, 39, 63,  6, 88,  1, 50, 90, 82, 76, 22,
       57, 88, 59])

In [33]:
sample_array.shape

(30,)

In [34]:
rand_array.argmin()

11

In [35]:
sample_array.reshape(1,30)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [36]:
sample_array.reshape(30,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29]])

In [37]:
sample_array.dtype

dtype('int32')

In [39]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
a1.T

array([[ 0.77412718, -0.32636817,  0.55473182],
       [-0.17186213,  1.05228812,  0.44863161]])

In [43]:
sample_array = np.arange(10,21)

In [44]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [45]:
sample_array[8]

18

In [46]:
sample_array[2:5]

array([12, 13, 14])

In [47]:
sample_array[[2,5]]

array([12, 15])

In [48]:
sample_array[1:2] = 100

In [49]:
sample_array

array([ 10, 100,  12,  13,  14,  15,  16,  17,  18,  19,  20])

In [50]:
sample_array = np.arange(10,21)

In [51]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [52]:
sample_array = np.arange(10,21)

sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [53]:
subset_sample_array = sample_array[0:7]

In [54]:
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [55]:
subset_sample_array[:] = 1001


In [56]:
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

In [57]:
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001,   17,   18,   19,   20])

In [58]:
copy_sample_array = sample_array.copy()

In [59]:
copy_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001,   17,   18,   19,   20])

In [60]:
copy_sample_array[:] = 10


In [61]:
copy_sample_array

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [62]:
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001,   17,   18,   19,   20])

In [63]:
sample_matrix = np.array(([50,20,1,23],[24,23,21,32],[76,54,32,12],[98,6,4,3]))

In [64]:
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 32],
       [76, 54, 32, 12],
       [98,  6,  4,  3]])

In [65]:
sample_matrix[0][3]

23

In [66]:
sample_matrix[0,3]

23

In [67]:
sample_matrix[3,:]

array([98,  6,  4,  3])

In [68]:
sample_matrix[3]

array([98,  6,  4,  3])

In [70]:
sample_matrix = sample_matrix = np.array(([50,20,1,23,34],[24,23,21,32,34],[76,54,32,98],[98,6,4,3,67],[12,23,34,56,67]))

In [71]:
sample_matrix

array([list([50, 20, 1, 23, 34]), list([24, 23, 21, 32, 34]),
       list([76, 54, 32, 98]), list([98, 6, 4, 3, 67]),
       list([12, 23, 34, 56, 67])], dtype=object)

In [72]:
sample_matrix = np.array(([50,20,1,23,34],[24,23,21,32,34],[76,54,32,98],[98,6,4,3,67],[12,23,34,56]))

In [73]:
sample_matrix

array([list([50, 20, 1, 23, 34]), list([24, 23, 21, 32, 34]),
       list([76, 54, 32, 98]), list([98, 6, 4, 3, 67]),
       list([12, 23, 34, 56, 67])], dtype=object)

In [75]:
sample_matrix = np.array(([50,20,1,23,34],[24,23,21,32,34],[76,54,32,98],[98,6,4,3,67],[12,23,34,56]))

In [76]:
sample_matrix

array([list([50, 20, 1, 23, 34]), list([24, 23, 21, 32, 34]),
       list([76, 54, 32, 98]), list([98, 6, 4, 3, 67]),
       list([12, 23, 34, 56])], dtype=object)

In [78]:
sample_matrix = np.array(([50,20,1,23,34],[24,23,21,32,34],[76,54,32,98],[98,6,4,3,67],[12,23,34,56]))

sample_matrix

In [80]:
sample_matrix = np.array(([50,20,1,23],[24,23,21,32],[76,54,32,12],[98,6,4,3]))

In [81]:
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 32],
       [76, 54, 32, 12],
       [98,  6,  4,  3]])

In [82]:
sample_matrix[:,(1,3)]

array([[20, 23],
       [23, 32],
       [54, 12],
       [ 6,  3]])

In [84]:
sample_matrix[:,(3,1)]

array([[23, 20],
       [32, 23],
       [12, 54],
       [ 3,  6]])

In [85]:
sample_array = np.arange(1,31)

In [86]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [87]:
sample_array < 10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [89]:
bool = sample_array < 10

In [90]:
bool

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [91]:
sample_array[bool]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
sample_array[sample_array < 10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
a = 11

In [94]:
sample_array[sample_array < a]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [95]:
sample_array + sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [96]:
sample_array - sample_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [97]:
sample_array * sample_array

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900])

In [98]:
sample_array / sample_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [99]:
10/sample_array

array([10.        ,  5.        ,  3.33333333,  2.5       ,  2.        ,
        1.66666667,  1.42857143,  1.25      ,  1.11111111,  1.        ,
        0.90909091,  0.83333333,  0.76923077,  0.71428571,  0.66666667,
        0.625     ,  0.58823529,  0.55555556,  0.52631579,  0.5       ,
        0.47619048,  0.45454545,  0.43478261,  0.41666667,  0.4       ,
        0.38461538,  0.37037037,  0.35714286,  0.34482759,  0.33333333])

In [100]:
sample_array + 1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [101]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [102]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [103]:
np.max(sample_array)

30

In [104]:
np.min(sample_array)

1

In [105]:
np.argmin(sample_array)

0

In [106]:
np.argmax(sample_array)

29

In [107]:
np.sin(sample_array)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111,
       -0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784,
       -0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525,
        0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175,
        0.76255845,  0.95637593,  0.27090579, -0.66363388, -0.98803162])

In [108]:
np.cos(sample_array)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153,
        0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791,
       -0.95765948, -0.27516334,  0.66031671,  0.98870462,  0.40808206,
       -0.54772926, -0.99996083, -0.53283302,  0.42417901,  0.99120281,
        0.64691932, -0.29213881, -0.96260587, -0.74805753,  0.15425145])

In [109]:
np.tan(sample_array)

array([ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,  1.15782128e+00,
       -3.38051501e+00, -2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
       -4.52315659e-01,  6.48360827e-01, -2.25950846e+02, -6.35859929e-01,
        4.63021133e-01,  7.24460662e+00, -8.55993401e-01,  3.00632242e-01,
        3.49391565e+00, -1.13731371e+00,  1.51589471e-01,  2.23716094e+00,
       -1.52749853e+00,  8.85165604e-03,  1.58815308e+00, -2.13489670e+00,
       -1.33526407e-01,  1.17875355e+00, -3.27370380e+00, -2.81429605e-01,
        8.87142844e-01, -6.40533120e+00])

In [110]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900], dtype=int32)

In [111]:
array = np.random.randn(6,6)

In [112]:
array

array([[ 0.00223981, -0.68432804, -0.97097614, -0.25432325,  1.81760696,
        -0.01518671],
       [ 0.71479   ,  1.43983595,  1.07102734,  1.67837837, -0.64208662,
        -0.13861534],
       [-1.43675713, -0.504699  , -1.28005893,  0.08365337,  0.00569551,
        -1.36265204],
       [ 1.88989613,  0.13714702, -0.89003581, -0.32389107, -0.23042479,
         0.50364819],
       [ 0.20874412,  0.00901707,  0.21090179, -1.25247299, -0.52459656,
        -0.08586932],
       [ 1.5287109 ,  0.14752721, -0.44089341, -1.45420145,  1.66115517,
        -0.11646583]])

In [114]:
np.round(array, decimals = 2)

array([[ 0.  , -0.68, -0.97, -0.25,  1.82, -0.02],
       [ 0.71,  1.44,  1.07,  1.68, -0.64, -0.14],
       [-1.44, -0.5 , -1.28,  0.08,  0.01, -1.36],
       [ 1.89,  0.14, -0.89, -0.32, -0.23,  0.5 ],
       [ 0.21,  0.01,  0.21, -1.25, -0.52, -0.09],
       [ 1.53,  0.15, -0.44, -1.45,  1.66, -0.12]])

In [115]:
np.std(sample_array)

8.65544144839919

In [117]:
np.var(sample_array)

74.91666666666667

In [118]:
np.std(array)

0.9390933536259539

In [119]:
np.mean(array)

0.01392890180438265

In [120]:
sports = np.array(['golf','cric','football','cric','Cric','fooseball'])

In [121]:
np.unique(sports)

array(['Cric', 'cric', 'fooseball', 'football', 'golf'], dtype='<U9')

In [122]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [123]:
simple_array = np.arange(0,20)

In [124]:
simple_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [125]:
np.save('sample_array', sample_array)

In [127]:
np.savez('2_arrays.npz', a = sample_array ,b = simple_array)

In [128]:
np.load('sample_array.npy')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [129]:
archive = np.load('2_arrays.npz')

In [130]:
archive

In [131]:
archive['a']

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [132]:
archive['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [134]:
np.savetxt('text_file.txt', sample_array, delimiter=',')

In [135]:
np.savetxt('text_file1.txt', sample_array, delimiter=',')

In [136]:
np.loadtxt('text_file.txt')

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30.])